### ISSUE TITLE
[Suggestion] Add more documentation for the project

### ISSUE THREAD

**Issue by LucileDT** [guitarxhero/FuckingClippy#18]
Hi! Feel free to edit this issue if you want to.

I think it would be nice to have more documentation about the project, specifically `what it is`, `how to use it` and `how to contribute to`.

### Edit the Readme
- [x] add more verbose explaining what is the project
- [ ] use more the word "clippy" to allow search engines to redirect to this project (depending on if you want to bring more people to find it)
- [x] add a section `what is this project`
- [x] add a section `how to use it` and linking to the wiki page
- [x] add pictures/screenshots/videos/gifs showing the project running

### Edit the Wiki
- [ ] add some verbose to invite visitors to click on pages links to visit the Wiki
- [x] add in requirements the Composite extension as specified in #3 
- [x] add a installation guide
- [x] add a full list of commands with arguments and description
- [x] add a page explaining `how people can contribute`
  - [x] how to report a bug
  - [x] how to code (commit messages, code standards...)
  - [ ] other things related to contribution (translation for example)

I know that's a lot of things so if you need someone, I would be happy to help you :slightly_smiling_face:

**Comment by dd86k** [comment]
Hello,

Thanks for the Issue! I'll do a few of these and come back and explain some stuff I didn't do.

**Comment by dd86k** [comment]
Time to explain what I haven't done and why.

> use more the word "clippy" to allow search engines to redirect to this project

Don't feel like it. I'd rather do SEO optimizations for my github portfolio.

>  add some verbose to invite visitors to click on pages links to visit the Wiki

Ehhh don't feel like it. I just hope people are curious enough to click on the Wiki link near the bottom of the README.

> other things related to contribution (translation for example)

Translations are far from being an actual thing at the moment, so that's why I haven't added a page on the Wiki just yet.

I'll close this and if [more] people asks for still then I guess I'll actually have to do those. Thanks for the suggestions too it's appreciated.

**Comment by LucileDT** [comment]
What you've done is perfect :+1: Thank you!
